//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCR.SGAG.Pruebas.wsSeguridad {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.itcr.ac.cr", ConfigurationName="wsSeguridad.SeguridadSoap")]
    public interface SeguridadSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itcr.ac.cr/ValidarUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ValidarUsuario(string login, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itcr.ac.cr/ValidarEstudiante", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ValidarEstudiante(string carne, string pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itcr.ac.cr/ValidarEstudianteBit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ValidarEstudianteBit(string carne, string pin, int codAplicacion, string codSede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itcr.ac.cr/EsEstudianteActivo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool EsEstudianteActivo(string carne);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itcr.ac.cr/EsEstudiante", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool EsEstudiante(string carne);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itcr.ac.cr/ValidarFuncionario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ValidarFuncionario(string usuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itcr.ac.cr/ValidarFuncionarioBit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ValidarFuncionarioBit(string usuario, string password, int codAplicacion, string codSede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itcr.ac.cr/ValidarFuncionarioBitSinCedula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ValidarFuncionarioBitSinCedula(string usuario, string password, int codAplicacion, string codSede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itcr.ac.cr/ComprobarUsuarioAD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ComprobarUsuarioAD(out string nombre, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itcr.ac.cr/ComprobarEstudiante", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ComprobarEstudiante(out string nombre, string carne);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itcr.ac.cr/ValidarUsuarioSistema", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ValidarUsuarioSistema(string usuario, string password, int codAplicacion, string codSede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itcr.ac.cr/TienePermisoFuncionalidad", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool TienePermisoFuncionalidad(int pCOD_APLICACION, int pCOD_FUNCIONALIDAD, string pID_USUARIO, string pCOD_SEDE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itcr.ac.cr/TieneAccesoAplicacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool TieneAccesoAplicacion(int pCOD_APLICACION, string pID_USUARIO, string pCOD_SEDE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itcr.ac.cr/ObtenerMenuUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ObtenerMenuUsuario(int pCod_Aplicacion, string pId_Usuario, string pCod_Sede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itcr.ac.cr/ObtenerCedula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ObtenerCedula(string pID_USUARIO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itcr.ac.cr/ObtenerDepartamento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ObtenerDepartamento(string pID_USUARIO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itcr.ac.cr/ObtenerNombreUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ObtenerNombreUsuario(string pID_USUARIO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itcr.ac.cr/ObtenerSedeUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ObtenerSedeUsuario(string pID_USUARIO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itcr.ac.cr/ObtenerListaSedes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ObtenerListaSedes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itcr.ac.cr/BuscarUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet BuscarUsuario(string txtBusqueda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itcr.ac.cr/BuscarUsuarioXCedula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string BuscarUsuarioXCedula(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itcr.ac.cr/BitacoraRegistrarUso", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void BitacoraRegistrarUso(int pCod_Aplicacion, int pCod_Funcionalidad, string pCod_Sede, ITCR.SGAG.Pruebas.wsSeguridad.eTipoEventoBitacora pTipo_Evento, string pId_Usuario, string pDatosEspecificos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itcr.ac.cr/CambiarPassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void CambiarPassword(string usuario, string passwordActual, string passwordNuevo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itcr.ac.cr/ObtenerUsuariosDeRol", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ObtenerUsuariosDeRol(int pCOD_ROL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itcr.ac.cr/ObtenerRolesDeUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ObtenerRolesDeUsuario(string pID_USUARIO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itcr.ac.cr/ConsultaBitacora", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ConsultaBitacora(int pCOD_APLICACION, string pID_USUARIO, System.DateTime pFHO_INICIO, System.DateTime pFHO_FIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itcr.ac.cr/getUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getUser(string pID_USUARIO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itcr.ac.cr/getUserByMail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getUserByMail(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itcr.ac.cr/findUserByName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet findUserByName(string texto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itcr.ac.cr/findUserByEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet findUserByEmail(string texto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itcr.ac.cr/TipoUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int TipoUsuario(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itcr.ac.cr/TDInformacionUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet TDInformacionUsuario(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.itcr.ac.cr/TDProfesores", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet TDProfesores(string ano, string modalidad, string periodo, string departamento, string sede);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.itcr.ac.cr")]
    public enum eTipoEventoBitacora {
        
        /// <remarks/>
        Acceso,
        
        /// <remarks/>
        UsoFuncionalidad,
        
        /// <remarks/>
        Error,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SeguridadSoapChannel : ITCR.SGAG.Pruebas.wsSeguridad.SeguridadSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SeguridadSoapClient : System.ServiceModel.ClientBase<ITCR.SGAG.Pruebas.wsSeguridad.SeguridadSoap>, ITCR.SGAG.Pruebas.wsSeguridad.SeguridadSoap {
        
        public SeguridadSoapClient() {
        }
        
        public SeguridadSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SeguridadSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeguridadSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeguridadSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ValidarUsuario(string login, string pass) {
            return base.Channel.ValidarUsuario(login, pass);
        }
        
        public bool ValidarEstudiante(string carne, string pin) {
            return base.Channel.ValidarEstudiante(carne, pin);
        }
        
        public bool ValidarEstudianteBit(string carne, string pin, int codAplicacion, string codSede) {
            return base.Channel.ValidarEstudianteBit(carne, pin, codAplicacion, codSede);
        }
        
        public bool EsEstudianteActivo(string carne) {
            return base.Channel.EsEstudianteActivo(carne);
        }
        
        public bool EsEstudiante(string carne) {
            return base.Channel.EsEstudiante(carne);
        }
        
        public bool ValidarFuncionario(string usuario, string password) {
            return base.Channel.ValidarFuncionario(usuario, password);
        }
        
        public bool ValidarFuncionarioBit(string usuario, string password, int codAplicacion, string codSede) {
            return base.Channel.ValidarFuncionarioBit(usuario, password, codAplicacion, codSede);
        }
        
        public bool ValidarFuncionarioBitSinCedula(string usuario, string password, int codAplicacion, string codSede) {
            return base.Channel.ValidarFuncionarioBitSinCedula(usuario, password, codAplicacion, codSede);
        }
        
        public bool ComprobarUsuarioAD(out string nombre, string usuario) {
            return base.Channel.ComprobarUsuarioAD(out nombre, usuario);
        }
        
        public bool ComprobarEstudiante(out string nombre, string carne) {
            return base.Channel.ComprobarEstudiante(out nombre, carne);
        }
        
        public bool ValidarUsuarioSistema(string usuario, string password, int codAplicacion, string codSede) {
            return base.Channel.ValidarUsuarioSistema(usuario, password, codAplicacion, codSede);
        }
        
        public bool TienePermisoFuncionalidad(int pCOD_APLICACION, int pCOD_FUNCIONALIDAD, string pID_USUARIO, string pCOD_SEDE) {
            return base.Channel.TienePermisoFuncionalidad(pCOD_APLICACION, pCOD_FUNCIONALIDAD, pID_USUARIO, pCOD_SEDE);
        }
        
        public bool TieneAccesoAplicacion(int pCOD_APLICACION, string pID_USUARIO, string pCOD_SEDE) {
            return base.Channel.TieneAccesoAplicacion(pCOD_APLICACION, pID_USUARIO, pCOD_SEDE);
        }
        
        public System.Data.DataSet ObtenerMenuUsuario(int pCod_Aplicacion, string pId_Usuario, string pCod_Sede) {
            return base.Channel.ObtenerMenuUsuario(pCod_Aplicacion, pId_Usuario, pCod_Sede);
        }
        
        public string ObtenerCedula(string pID_USUARIO) {
            return base.Channel.ObtenerCedula(pID_USUARIO);
        }
        
        public string ObtenerDepartamento(string pID_USUARIO) {
            return base.Channel.ObtenerDepartamento(pID_USUARIO);
        }
        
        public string ObtenerNombreUsuario(string pID_USUARIO) {
            return base.Channel.ObtenerNombreUsuario(pID_USUARIO);
        }
        
        public string ObtenerSedeUsuario(string pID_USUARIO) {
            return base.Channel.ObtenerSedeUsuario(pID_USUARIO);
        }
        
        public System.Data.DataSet ObtenerListaSedes() {
            return base.Channel.ObtenerListaSedes();
        }
        
        public System.Data.DataSet BuscarUsuario(string txtBusqueda) {
            return base.Channel.BuscarUsuario(txtBusqueda);
        }
        
        public string BuscarUsuarioXCedula(string cedula) {
            return base.Channel.BuscarUsuarioXCedula(cedula);
        }
        
        public void BitacoraRegistrarUso(int pCod_Aplicacion, int pCod_Funcionalidad, string pCod_Sede, ITCR.SGAG.Pruebas.wsSeguridad.eTipoEventoBitacora pTipo_Evento, string pId_Usuario, string pDatosEspecificos) {
            base.Channel.BitacoraRegistrarUso(pCod_Aplicacion, pCod_Funcionalidad, pCod_Sede, pTipo_Evento, pId_Usuario, pDatosEspecificos);
        }
        
        public void CambiarPassword(string usuario, string passwordActual, string passwordNuevo) {
            base.Channel.CambiarPassword(usuario, passwordActual, passwordNuevo);
        }
        
        public System.Data.DataSet ObtenerUsuariosDeRol(int pCOD_ROL) {
            return base.Channel.ObtenerUsuariosDeRol(pCOD_ROL);
        }
        
        public System.Data.DataSet ObtenerRolesDeUsuario(string pID_USUARIO) {
            return base.Channel.ObtenerRolesDeUsuario(pID_USUARIO);
        }
        
        public System.Data.DataSet ConsultaBitacora(int pCOD_APLICACION, string pID_USUARIO, System.DateTime pFHO_INICIO, System.DateTime pFHO_FIN) {
            return base.Channel.ConsultaBitacora(pCOD_APLICACION, pID_USUARIO, pFHO_INICIO, pFHO_FIN);
        }
        
        public System.Data.DataSet getUser(string pID_USUARIO) {
            return base.Channel.getUser(pID_USUARIO);
        }
        
        public System.Data.DataSet getUserByMail(string correo) {
            return base.Channel.getUserByMail(correo);
        }
        
        public System.Data.DataSet findUserByName(string texto) {
            return base.Channel.findUserByName(texto);
        }
        
        public System.Data.DataSet findUserByEmail(string texto) {
            return base.Channel.findUserByEmail(texto);
        }
        
        public int TipoUsuario(string usuario) {
            return base.Channel.TipoUsuario(usuario);
        }
        
        public System.Data.DataSet TDInformacionUsuario(string cedula) {
            return base.Channel.TDInformacionUsuario(cedula);
        }
        
        public System.Data.DataSet TDProfesores(string ano, string modalidad, string periodo, string departamento, string sede) {
            return base.Channel.TDProfesores(ano, modalidad, periodo, departamento, sede);
        }
    }
}
